version: '3.8'
services:
  p-art:
    build: .
    image: ghcr.io/ljam96/p-art:latest
    container_name: p-art
    ports:
      - "5000:5000"
    environment:
      PLEX_URL: "http://localhost:32400"
      PLEX_TOKEN: ""
      TMDB_API_KEY: ""
      FANART_API_KEY: ""
      OMDB_API_KEY: ""
      TVDB_API_KEY: ""
      LIBRARIES: "all"
      INCLUDE_BACKGROUNDS: "true"
      OVERWRITE: "false"
      ONLY_MISSING: "true"
      DRY_RUN: "true"
      PROVIDER_PRIORITY: "tmdb,fanart,omdb,tvdb"
      ARTWORK_LANGUAGE: "en"
      #CRON_SCHEDULE: "0 2 * * *"
